name: Run docker-compose-viz-mermaid

on:
  push:
    branches:
      - main

jobs:
  run-docker-compose-viz-mermaid:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run docker-compose-viz-mermaid
        run: |
          docker run --rm -v $PWD:/input derlin/docker-compose-viz-mermaid /input/docker-compose.yml > output.mmd
